services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Code711\Code711Housekeeping\:
    resource: '../Classes/*'

  Code711\Code711Housekeeping\Command\UpdateVersionsCommand:
    tags:
      - name: 'console.command'
        command: 'housekeeping:update'
        description: 'update versions'
        schedulable: true

  dashboard.widget.projects:
    class: 'Code711\Code711Housekeeping\Widgets\ProjectsWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $options:
        groups:
        sorting:
          - 'severity desc'
          - 'version asc'
          - 'title asc'
    tags:
      - name: dashboard.widget
        identifier: 'projects'
        groupNames: 'housekeeping'
        title: 'LLL:EXT:code711_housekeeping/Resources/Private/Language/locallang.xlf:widgets.projects.title'
        description: 'LLL:EXT:code711_housekeeping/Resources/Private/Language/locallang.xlf:widgets.projects.description'
        iconIdentifier: 'content-widget-text'
        height: 'large'
        width: 'medium'
  dashboard.widget.phpversions:
    class: 'Code711\Code711Housekeeping\Widgets\PhpVersionsWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $options:
        groups:
        sorting:
          - 'php asc'
          - 'title asc'
    tags:
      - name: dashboard.widget
        identifier: 'phpversions'
        groupNames: 'housekeeping'
        title: 'LLL:EXT:code711_housekeeping/Resources/Private/Language/locallang.xlf:widgets.phpversions.title'
        description: 'LLL:EXT:code711_housekeeping/Resources/Private/Language/locallang.xlf:widgets.phpversions.description'
        iconIdentifier: 'content-widget-text'
        height: 'large'
        width: 'small'
